# Defaults:

# 1) If a field is not listed here, it can't be used as fiter or group by.
# 2) When listing a date field (eg: created_at):
#   a) The following filters will be enabled: created_at_since and created_at_until
#   b) The following groups will be enabled: year(created_at), month(created_at), day(created_at)
# 3) When listing a string of multi_field type field:
#   a) A 'wildcard' filter with the same name will be enabled.
#   b) A 'flat' group with the same name will be enabled.
# 4) When listing an integer type field:
#   a) A 'match' filter with the same name will be enabled.
#   b) A 'flat' group with the same name will be enabled.
# 5) If the field name ends with '_id', the default group and filter will be created with the name without the '_id': institution_id => institution.
# 6) Range grouping also implies flat grouping, and it will depend on what is received on the request.
# 7) If the default group or filter is not needed, this must be overriden with the keyword 'none'.
# 8) The default field type is 'string'
# 9) If a filter or group has no name, it will be the same as the field name, as specified in (5).
# 10) If a filter or group has no type, it will be the default type as specified in (3) and (4).
# 11) If a filter or group is added with the sole option 'include_default: true', then the default filter or group will be added to the filters or groups array, as specified in (3), (4), and (5).
# 12) If a field of type location is defined, the filters and groupings are going to be the following:
#   a) a filter with the same name
#   b) a grouping with the name of '#{default_name}_admin_level'

- name: test.start_time
  filter_parameter_definition:
    - name: since
      type: range
      boundary: from
      options:
        include_lower: true
    - name: until
      type: range
      boundary: to
      options:
        include_lower: true
- name: test.id
  group_parameter_definition: none
- name: test.uuid
  filter_parameter_definition:
    - type: match
  group_parameter_definition: none
- name: location.parents
  filter_parameter_definition:
    - name: location.id
      type: match
- name: location.admin_levels
  group_parameter_definition:
    - name: location.admin_level
      type: location
- name: test.patient_age
  filter_parameter_definition:
    - include_default: true
    - name: min_age
      type: range
      boundary: from
      options:
        include_lower: true
    - name: max_age
      type: range
      boundary: to
      options:
        include_upper: true
  group_parameter_definition:
    - type: range
